using System;

namespace Sensus.Captions;

// 40 ms RMS envelope of the original JackInTheBoxTheme (44100 Hz, 1890304 frames).
// A visual loudness trace, not an AI countdown or predicted pop time.
// Generated by scripts/generate_winding_envelope.py; no audio decoding in the HUD.
internal static class WindingEnvelope
{
    private static readonly byte[] Levels = Convert.FromBase64String("WXd/m/+vcFdFOigdFgsugXxTMqCIZlhHNyYXFxMPEQsUvIp2VG7PmoRZ4LZzTFTPjnFDqoafekktLiMeFBgTDCbHU5dU/72BrmdTKzIrHBwWIZxtYl+1m35tUDclIx0gHRYc25dzaf/SlnZNNCslHhcPCQcGBQMb7JpwfVszHyAjGRQQDAYEBAQDAgmskqWFTC4wKCEWGh1rVl1e65mCalI7LCoeExMu/86JotWffMWvjGitlH1q4bPMik06OCQdKCA392i6zP+ix1tiNkQmLx+KlJZv8qOSZUE9NCwgFSrftoXfy5ByVUYvGhQPCwcGBRiUWjtGNRoUEw8JDAoFBAQCFtt9YE4sGTmNYzJDRkJ77JxsQyghdHNAL4ZbQf+8hYKBWXL7pmyPaWS8ml9GLCJBw619gZtmyoFXPCMkQv+ygsqMbNKTVy8iG3vGiWGYb4SzaTonGxuWbjl0dXHGg1E7JRh5e0cuHRB9xYNLMCx+fktCbVyX9ZhyQCtzbUZSa1WmeFduZFH1q2V9YFj/tJxlPWfOvF7jh9WqgkkvJcnVnmVBWeyHV0E1g39Xk5+L5odXjGyZlGA5IBnlvpxcOICVWzYsMdePRzsjXlc5NShQln9njWm1a1GAVaysgFM3iv+C2reusXdCQz2CUikbGWyXTqRtpJtXh0ihx2e6XMBzem/Tq/+BxnKbaU0vLWeRbIR0lI1JNjGXjapbXpJdTnesv7uRYoeEYW+Go7jOYXK3fY9uhKnltKv/lm15XpWdoNfa2myQh5Gd9NL6tZt1fZGJn5awsYBpTIeLo4BUmWs9N2tmfWI1hV5Nhf+itKN/e3p9aNWqh4edanJenJWboVOXd2Nv+vbBeZqPo3eZrMuBZaN/d//f4bR8tZVWZ5aHpn10ll45bmt/VmuMZ1x3fIVOa4VUXnSPkXmagXNco7uZk413gYjAhf+BhLqCZc2kgX+Xco5ujcRweZ+IUGSFnH13c4llfIaDZHVuzojt/YOws4F05JaftHFGp8GbqJCCepCYq6yXhZiAboKae3SNc4v/nGufcE57fl9tcGtMXmJWVVVhlpt7m4Z0ov+IosKEiqiufnSSl22Fi3GwmpyajGuskZd4q7fJnrOGm2aNk2CgsYqJiZKcgpOQf7aHeKu3gcSg9e6ru9W7o45xdG9fgoNwe3CzeG+diHKKhHyXeYTEtnf/nHmsn2CftnShfGx7qLq2pcDBx+vQwZeSr4WQjJWNam53V2OWgHSTeH6Yk42FhLiGldK2dL2UZ5CPgX13anyOvIasdcPIgP/MicW2b6RzbnBRUl5LOkc2ND06NzMyIyEcFRcaGR0ZHRoZGRUPDhIgIB0QCQYEAgIBAQEBAAABAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==");
    internal static float At(float seconds)
    {
        if(float.IsNaN(seconds) || seconds<0 || seconds>=42.864036f) return 0;
        float sample=seconds*25;
        int index=(int)sample;
        if(index>=Levels.Length) return 0;
        float a=Levels[index]/255f;
        float b=Levels[Math.Min(index+1,Levels.Length-1)]/255f;
        return a+(b-a)*(sample-index);
    }
    internal static float Urgency(float seconds) => float.IsNaN(seconds) ? 0 : Math.Max(0,Math.Min(1,seconds/42.864036f));
    internal static float Shake(float seconds,bool live,bool lowMotion) =>
        lowMotion || !live || seconds<0 ? 0 : (2+12*Urgency(seconds))*(float)Math.Sin(2*Math.PI*(2*seconds+0.08f*seconds*seconds));
    internal static float Scale(float envelope,bool live,bool lowMotion) =>
        lowMotion || !live ? 1 : 1+0.14f*Math.Max(0,Math.Min(1,envelope));
}
