// Generated by scripts/generate_creature_bindings.py. Direct audio fields only.
using UnityEngine;
using GameNetcodeStuff;
using Sensus.Captions;

namespace Sensus.Audio;

internal static class CreatureBindings
{
    internal static void Register(Component component)
    {
        switch (component)
        {
            case MouthDogAI e:
            {
                AudioRegistry.Source(e.creatureVoice, Cue.Creature, e, true);
                AudioRegistry.Source(e.creatureSFX, Cue.Creature, e, true);
                AudioRegistry.Clips(e.screamSFX, Cue.Roar);
                AudioRegistry.Clips(e.breathingSFX, Cue.Breathing);
                AudioRegistry.Clips(e.killPlayerSFX, Cue.Impact);
                break;
            }
            case SandWormAI e:
            {
                AudioRegistry.Source(e.creatureVoice, Cue.Creature, e, true);
                AudioRegistry.Source(e.creatureSFX, Cue.Creature, e, true);
                AudioRegistry.Source(e.groundAudio, Cue.Creature, e, false);
                AudioRegistry.Clips(e.groundRumbleSFX, Cue.GroundRumble);
                AudioRegistry.Clips(e.ambientRumbleSFX, Cue.Underground);
                AudioRegistry.Clips(e.hitGroundSFX, Cue.GroundImpact);
                AudioRegistry.Clips(e.emergeFromGroundSFX, Cue.Emerge);
                AudioRegistry.Clips(e.roarSFX, Cue.Roar);
                break;
            }
            case JesterAI e:
            {
                AudioRegistry.Source(e.creatureVoice, Cue.Creature, e, true);
                AudioRegistry.Source(e.creatureSFX, Cue.Creature, e, true);
                AudioRegistry.Source(e.farAudio, Cue.Creature, e, true);
                AudioRegistry.Clips(e.popGoesTheWeaselTheme, Cue.Music);
                AudioRegistry.Clips(e.popUpSFX, Cue.BoxOpen);
                AudioRegistry.Clips(e.screamingSFX, Cue.Screaming);
                AudioRegistry.Clips(e.killPlayerSFX, Cue.Impact);
                break;
            }
            case NutcrackerEnemyAI e:
            {
                AudioRegistry.Source(e.creatureVoice, Cue.Creature, e, true);
                AudioRegistry.Source(e.creatureSFX, Cue.Creature, e, true);
                AudioRegistry.Source(e.torsoTurnAudio, Cue.MechanicalTurn, e, false);
                AudioRegistry.Source(e.longRangeAudio, Cue.Creature, e, true);
                AudioRegistry.Clips(e.torsoFinishTurningClips, Cue.MechanicalTurn);
                AudioRegistry.Clips(e.aimSFX, Cue.Aim);
                AudioRegistry.Clips(e.kickSFX, Cue.NutcrackerKick);
                break;
            }
            case CaveDwellerAI e:
            {
                AudioRegistry.Source(e.creatureVoice, Cue.Creature, e, true);
                AudioRegistry.Source(e.creatureSFX, Cue.Creature, e, true);
                AudioRegistry.Source(e.walkingAudio, Cue.Footsteps, e, false);
                AudioRegistry.Clips(e.growlSFX, Cue.Growl);
                AudioRegistry.Clips(e.fakeCrySFX, Cue.Crying);
                AudioRegistry.Source(e.clickingAudio1, Cue.Clicking, e, true);
                AudioRegistry.Source(e.clickingAudio2, Cue.Clicking, e, true);
                AudioRegistry.Source(e.screamAudio, Cue.Screaming, e, false);
                AudioRegistry.Source(e.screamAudioNonDiagetic, Cue.Screaming, e, false);
                AudioRegistry.Clips(e.cooldownSFX, Cue.Creature);
                AudioRegistry.Source(e.babyCryingAudio, Cue.Crying, e, false);
                AudioRegistry.Source(e.babyVoice, Cue.Crying, e, false);
                AudioRegistry.Clips(e.squirmingSFX, Cue.Rustling);
                AudioRegistry.Clips(e.transformationSFX, Cue.Transformation);
                AudioRegistry.Clips(e.scaredBabyVoiceSFX, Cue.Crying);
                AudioRegistry.Clips(e.biteSFX, Cue.Bite);
                AudioRegistry.Clips(e.pukeSFX, Cue.Liquid);
                break;
            }
            case DressGirlAI e:
            {
                AudioRegistry.Source(e.creatureVoice, Cue.Creature, e, true);
                AudioRegistry.Source(e.creatureSFX, Cue.Creature, e, true);
                AudioRegistry.Clips(e.appearStaringSFX, Cue.Creature);
                AudioRegistry.Clips(e.skipWalkSFX, Cue.SkippingFootsteps);
                AudioRegistry.Clips(e.breathingSFX, Cue.Breathing);
                AudioRegistry.Source(e.heartbeatMusic, Cue.Heartbeat, e, false);
                break;
            }
            case ClaySurgeonAI e:
            {
                AudioRegistry.Source(e.creatureVoice, Cue.Creature, e, true);
                AudioRegistry.Source(e.creatureSFX, Cue.Creature, e, true);
                AudioRegistry.Source(e.musicAudio, Cue.March, e, false);
                AudioRegistry.Source(e.musicAudio2, Cue.March, e, false);
                AudioRegistry.Clips(e.snareDrum, Cue.Drum);
                AudioRegistry.Clips(e.paradeClips, Cue.March);
                AudioRegistry.Clips(e.snipScissors, Cue.Snip);
                break;
            }
            case SpringManAI e:
            {
                AudioRegistry.Source(e.creatureVoice, Cue.Creature, e, true);
                AudioRegistry.Source(e.creatureSFX, Cue.Creature, e, true);
                AudioRegistry.Clips(e.springNoises, Cue.Spring);
                AudioRegistry.Clips(e.enterCooldownSFX, Cue.SpringRetract);
                break;
            }
            case FlowermanAI e:
            {
                AudioRegistry.Source(e.creatureVoice, Cue.Creature, e, true);
                AudioRegistry.Source(e.creatureSFX, Cue.Creature, e, true);
                AudioRegistry.Source(e.creatureAngerVoice, Cue.Growl, e, false);
                AudioRegistry.Source(e.crackNeckAudio, Cue.Crack, e, false);
                AudioRegistry.Clips(e.crackNeckSFX, Cue.Crack);
                break;
            }
            case CrawlerAI e:
            {
                AudioRegistry.Source(e.creatureVoice, Cue.Creature, e, true);
                AudioRegistry.Source(e.creatureSFX, Cue.Creature, e, true);
                AudioRegistry.Clips(e.shortRoar, Cue.Roar);
                AudioRegistry.Clips(e.hitWallSFX, Cue.Impact);
                AudioRegistry.Clips(e.bitePlayerSFX, Cue.Bite);
                AudioRegistry.Clips(e.eatPlayerSFX, Cue.Bite);
                AudioRegistry.Clips(e.hitCrawlerSFX, Cue.CreatureHit);
                AudioRegistry.Clips(e.longRoarSFX, Cue.Roar);
                break;
            }
            case CentipedeAI e:
            {
                AudioRegistry.Source(e.creatureVoice, Cue.Creature, e, true);
                AudioRegistry.Source(e.creatureSFX, Cue.Creature, e, true);
                AudioRegistry.Clips(e.fallShriek, Cue.Screaming);
                AudioRegistry.Clips(e.hitGroundSFX, Cue.Impact);
                AudioRegistry.Clips(e.hitCentipede, Cue.CreatureHit);
                AudioRegistry.Clips(e.shriekClips, Cue.Screaming);
                AudioRegistry.Source(e.clingingToPlayer2DAudio, Cue.Cling, e, false);
                AudioRegistry.Clips(e.clingToPlayer3D, Cue.OtherCling);
                break;
            }
            case SandSpiderAI e:
            {
                AudioRegistry.Source(e.creatureVoice, Cue.Creature, e, true);
                AudioRegistry.Source(e.creatureSFX, Cue.Creature, e, true);
                AudioRegistry.Clips(e.footstepSFX, Cue.SkitterFootsteps);
                AudioRegistry.Source(e.footstepAudio, Cue.SkitterFootsteps, e, true);
                AudioRegistry.Clips(e.hitWebSFX, Cue.Web);
                AudioRegistry.Clips(e.attackSFX, Cue.Bite);
                AudioRegistry.Clips(e.spoolPlayerSFX, Cue.Rustling);
                AudioRegistry.Clips(e.hangPlayerSFX, Cue.Rustling);
                AudioRegistry.Clips(e.breakWebSFX, Cue.Web);
                AudioRegistry.Clips(e.hitSpiderSFX, Cue.CreatureHit);
                break;
            }
            case HoarderBugAI e:
            {
                AudioRegistry.Source(e.creatureVoice, Cue.Creature, e, true);
                AudioRegistry.Source(e.creatureSFX, Cue.Creature, e, true);
                AudioRegistry.Clips(e.chitterSFX, Cue.Chitter);
                AudioRegistry.Clips(e.angryScreechSFX, Cue.Screaming);
                AudioRegistry.Clips(e.angryVoiceSFX, Cue.Chitter);
                AudioRegistry.Clips(e.bugFlySFX, Cue.Wings);
                AudioRegistry.Clips(e.hitPlayerSFX, Cue.Impact);
                break;
            }
            case BlobAI e:
            {
                AudioRegistry.Source(e.creatureVoice, Cue.Creature, e, true);
                AudioRegistry.Source(e.creatureSFX, Cue.Creature, e, true);
                AudioRegistry.Source(e.movableAudioSource, Cue.Slime, e, false);
                AudioRegistry.Clips(e.agitatedSFX, Cue.Slime);
                AudioRegistry.Clips(e.jiggleSFX, Cue.Slime);
                AudioRegistry.Clips(e.hitSlimeSFX, Cue.SlimeHit);
                AudioRegistry.Clips(e.killPlayerSFX, Cue.Liquid);
                AudioRegistry.Clips(e.idleSFX, Cue.Slime);
                break;
            }
            case PufferAI e:
            {
                AudioRegistry.Source(e.creatureVoice, Cue.Creature, e, true);
                AudioRegistry.Source(e.creatureSFX, Cue.Creature, e, true);
                AudioRegistry.Clips(e.footstepsSFX, Cue.Footsteps);
                AudioRegistry.Clips(e.frightenSFX, Cue.Chitter);
                AudioRegistry.Clips(e.stomp, Cue.Impact);
                AudioRegistry.Clips(e.angry, Cue.Chitter);
                AudioRegistry.Clips(e.puff, Cue.Spray);
                AudioRegistry.Clips(e.nervousMumbling, Cue.Chitter);
                AudioRegistry.Clips(e.rattleTail, Cue.Rattle);
                AudioRegistry.Clips(e.bitePlayerSFX, Cue.Bite);
                break;
            }
            case ButlerEnemyAI e:
            {
                AudioRegistry.Source(e.creatureVoice, Cue.Creature, e, true);
                AudioRegistry.Source(e.creatureSFX, Cue.Creature, e, true);
                AudioRegistry.Source(e.ambience1, Cue.Creature, e, false);
                AudioRegistry.Source(e.buzzingAmbience, Cue.Buzz, e, false);
                AudioRegistry.Source(e.sweepingAudio, Cue.Sweeping, e, false);
                AudioRegistry.Clips(e.footsteps, Cue.Footsteps);
                AudioRegistry.Clips(e.broomSweepSFX, Cue.Sweeping);
                AudioRegistry.Source(e.popAudio, Cue.Burst, e, true);
                AudioRegistry.Source(e.popAudioFar, Cue.Burst, e, true);
                AudioRegistry.Source(e.ambience2, Cue.Creature, e, false);
                AudioRegistry.Source(ButlerEnemyAI.murderMusicAudio, Cue.TensionMusic, e, false);
                break;
            }
            case ButlerBeesEnemyAI e:
            {
                AudioRegistry.Source(e.creatureVoice, Cue.Buzz, e, true);
                AudioRegistry.Source(e.creatureSFX, Cue.Buzz, e, true);
                AudioRegistry.Source(e.buzzing, Cue.Buzz, e, true);
                break;
            }
            case MaskedPlayerEnemy e:
            {
                AudioRegistry.RegisterFootsteps();
                AudioRegistry.Source(e.movementAudio, Cue.Creature, e, false);
                break;
            }
            case StingrayAI e:
            {
                AudioRegistry.Source(e.creatureVoice, Cue.Creature, e, true);
                AudioRegistry.Source(e.creatureSFX, Cue.Creature, e, true);
                AudioRegistry.Source(e.poisonAudio, Cue.VisorHit, e, false);
                AudioRegistry.Source(e.floppingAudio, Cue.Flopping, e, false);
                AudioRegistry.Source(e.slidingAudio, Cue.Sliding, e, false);
                AudioRegistry.Clips(e.spitSFX, Cue.Spit);
                AudioRegistry.Source(e.whiningAudio, Cue.Whining, e, false);
                break;
            }
            case CadaverGrowthAI e:
            {
                AudioRegistry.Source(e.creatureVoice, Cue.Creature, e, true);
                AudioRegistry.Source(e.creatureSFX, Cue.Creature, e, true);
                AudioRegistry.Source(e.destroyAudio, Cue.PlantClear, e, false);
                AudioRegistry.Source(e.plantAudio, Cue.PlantGrowth, e, false);
                AudioRegistry.Source(e.bloomMusic, Cue.TensionMusic, e, false);
                AudioRegistry.Source(e.sporeAmbienceSource, Cue.SporeCloud, e, false);
                AudioRegistry.Clips(e.healPlayerSFX, Cue.BloomTreatment);
                AudioRegistry.Source(e.vinesInHeadAudio, Cue.HeadRustling, e, false);
                AudioRegistry.Clips(e.vinesInHeadSFX, Cue.HeadRustling);
                break;
            }
            case CadaverBloomAI e:
            {
                AudioRegistry.Source(e.creatureVoice, Cue.Creature, e, true);
                AudioRegistry.Source(e.creatureSFX, Cue.Creature, e, true);
                AudioRegistry.Clips(e.burstSFX, Cue.BloomBurst);
                AudioRegistry.Source(e.breathingSFX, Cue.BloomBreath, e, false);
                AudioRegistry.Source(e.burstSource, Cue.BloomChomp, e, false);
                AudioRegistry.Clips(e.plantFeetHit, Cue.GroundImpact);
                AudioRegistry.Clips(e.chestBurst, Cue.BloomChestOpen);
                AudioRegistry.Clips(e.chestPlantRoars, Cue.BloomRoar);
                AudioRegistry.Clips(e.bitePlayer, Cue.BloomChomp);
                break;
            }
            case ForestGiantAI e:
            {
                AudioRegistry.Source(e.creatureVoice, Cue.Creature, e, true);
                AudioRegistry.Source(e.creatureSFX, Cue.Creature, e, true);
                AudioRegistry.Source(e.farWideSFX, Cue.Creature, e, true);
                AudioRegistry.Clips(e.giantFall, Cue.GroundImpact);
                AudioRegistry.Clips(e.giantCry, Cue.Roar);
                AudioRegistry.Source(e.giantBurningAudio, Cue.Fire, e, false);
                break;
            }
            case BaboonBirdAI e:
            {
                AudioRegistry.Source(e.creatureVoice, Cue.Creature, e, true);
                AudioRegistry.Source(e.creatureSFX, Cue.Creature, e, true);
                AudioRegistry.Source(e.aggressionAudio, Cue.Chitter, e, false);
                AudioRegistry.Clips(e.cawScreamSFX, Cue.Screaming);
                AudioRegistry.Clips(e.cawLaughSFX, Cue.Cackle);
                break;
            }
            case RedLocustBees e:
            {
                AudioRegistry.Source(e.creatureVoice, Cue.Buzz, e, true);
                AudioRegistry.Source(e.creatureSFX, Cue.Buzz, e, true);
                AudioRegistry.Source(e.beesIdle, Cue.Buzz, e, true);
                AudioRegistry.Source(e.beesDefensive, Cue.BuzzAlert, e, true);
                AudioRegistry.Source(e.beesAngry, Cue.BuzzAttack, e, true);
                AudioRegistry.Source(e.beeZapAudio, Cue.Electric, e, false);
                break;
            }
            case RadMechAI e:
            {
                AudioRegistry.Source(e.creatureVoice, Cue.Creature, e, true);
                AudioRegistry.Source(e.creatureSFX, Cue.Creature, e, true);
                AudioRegistry.Clips(e.spotlightOff, Cue.MechanicalAlert);
                AudioRegistry.Clips(e.spotlightFlicker, Cue.MechanicalAlert);
                AudioRegistry.Source(e.LocalLRADAudio, Cue.Broadcast, e, false);
                AudioRegistry.Source(e.LocalLRADAudio2, Cue.Broadcast, e, false);
                AudioRegistry.Clips(e.shootGunSFX, Cue.Launch);
                AudioRegistry.Clips(e.largeExplosionSFX, Cue.Explosion);
                AudioRegistry.Source(e.explosionAudio, Cue.Explosion, e, false);
                AudioRegistry.Source(e.blowtorchAudio, Cue.Fire, e, false);
                AudioRegistry.Source(e.flyingDistantAudio, Cue.Engine, e, false);
                AudioRegistry.Source(e.spotlightOnAudio, Cue.MechanicalAlert, e, false);
                AudioRegistry.Source(e.chargeForwardAudio, Cue.Engine, e, false);
                AudioRegistry.Source(e.engineSFX, Cue.Engine, e, false);
                break;
            }
            case BushWolfEnemy e:
            {
                AudioRegistry.Source(e.creatureVoice, Cue.Creature, e, true);
                AudioRegistry.Source(e.creatureSFX, Cue.Creature, e, true);
                AudioRegistry.Clips(e.snarlSFX, Cue.WolfSnarl);
                AudioRegistry.Clips(e.growlSFX, Cue.WolfGrowl);
                AudioRegistry.Source(e.growlAudio, Cue.WolfGrowl, e, false);
                AudioRegistry.Clips(e.shootTongueSFX, Cue.WolfTongue);
                AudioRegistry.Source(e.tongueAudio, Cue.WolfPull, e, false);
                AudioRegistry.Clips(e.tongueShootSFX, Cue.WolfTongue);
                AudioRegistry.Clips(e.killSFX, Cue.WolfAttack);
                AudioRegistry.Source(e.callClose, Cue.WolfCall, e, true);
                AudioRegistry.Source(e.callFar, Cue.WolfCall, e, true);
                AudioRegistry.Clips(e.callsClose, Cue.WolfCall);
                AudioRegistry.Clips(e.callsFar, Cue.WolfCall);
                AudioRegistry.Clips(e.hitBushWolfSFX, Cue.WolfHit);
                break;
            }
            case PumaAI e:
            {
                AudioRegistry.Source(e.creatureVoice, Cue.Creature, e, true);
                AudioRegistry.Source(e.creatureSFX, Cue.Creature, e, true);
                AudioRegistry.Clips(e.climbTreeSFX1, Cue.Climbing);
                AudioRegistry.Clips(e.climbTreeSFX2, Cue.Climbing);
                AudioRegistry.Clips(e.pumaLeapSFX1, Cue.Rustling);
                AudioRegistry.Clips(e.pumaLeapSFX2, Cue.Rustling);
                AudioRegistry.Clips(e.pumaGrowlSFX, Cue.Growl);
                AudioRegistry.Source(e.growlSource, Cue.Growl, e, false);
                AudioRegistry.Clips(e.pumaRunSFX, Cue.Footsteps);
                AudioRegistry.Clips(e.pumaFootstepSFX, Cue.Footsteps);
                AudioRegistry.Source(e.footstepSource, Cue.Footsteps, e, true);
                AudioRegistry.Clips(e.attackScream, Cue.Screaming);
                AudioRegistry.Clips(e.dropSFX, Cue.Impact);
                AudioRegistry.Source(e.attackSFX, Cue.Screaming, e, true);
                AudioRegistry.Source(e.attackSFXFaraway, Cue.Screaming, e, true);
                AudioRegistry.Clips(e.scratchSFX, Cue.Scratch);
                break;
            }
            case GiantKiwiAI e:
            {
                AudioRegistry.Source(e.creatureVoice, Cue.Creature, e, true);
                AudioRegistry.Source(e.creatureSFX, Cue.Creature, e, true);
                AudioRegistry.Clips(e.footstepSFX, Cue.Footsteps);
                AudioRegistry.Clips(e.footstepBassSFX, Cue.Footsteps);
                AudioRegistry.Clips(e.peckTreeSFX, Cue.Peck);
                AudioRegistry.Source(e.peckAudio, Cue.Peck, e, false);
                AudioRegistry.Source(e.longDistanceAudio, Cue.Creature, e, true);
                AudioRegistry.Clips(e.attackSFX, Cue.CreatureAttack);
                AudioRegistry.Clips(e.screamSFX, Cue.BirdCall);
                AudioRegistry.Clips(e.squawkSFX, Cue.BirdCall);
                AudioRegistry.Clips(e.wakeUpSFX, Cue.BirdCall);
                AudioRegistry.Clips(e.breakAndEnter, Cue.DoorImpact);
                AudioRegistry.Clips(e.shipAlarm, Cue.Alarm);
                AudioRegistry.Source(e.breakDownDoorAudio, Cue.DoorImpact, e, false);
                AudioRegistry.Source(e.birdNestAmbience, Cue.BirdCall, e, false);
                break;
            }
            case FlowerSnakeEnemy e:
            {
                AudioRegistry.Source(e.creatureVoice, Cue.Creature, e, true);
                AudioRegistry.Source(e.creatureSFX, Cue.Creature, e, true);
                AudioRegistry.Source(e.flappingAudio, Cue.Wings, e, false);
                break;
            }
            case DoublewingAI e:
            {
                AudioRegistry.Source(e.creatureVoice, Cue.BirdCall, e, true);
                AudioRegistry.Source(e.creatureSFX, Cue.BirdCall, e, true);
                AudioRegistry.Source(e.flappingAudio, Cue.Wings, e, false);
                AudioRegistry.Clips(e.birdScreechSFX, Cue.BirdCall);
                AudioRegistry.Clips(e.birdHitGroundSFX, Cue.Impact);
                break;
            }
            case DocileLocustBeesAI e:
            {
                AudioRegistry.Source(e.creatureVoice, Cue.Buzz, e, true);
                AudioRegistry.Source(e.creatureSFX, Cue.Buzz, e, true);
                break;
            }
            case DepositItemsDesk e:
            {
                AudioRegistry.Source(e.deskAudio, Cue.MechanicalAlert, e, false);
                AudioRegistry.Source(e.wallAudio, Cue.WallRumble, e, false);
                AudioRegistry.Source(e.constantWallAudio, Cue.WallRumble, e, false);
                AudioRegistry.Source(e.doorWindowAudio, Cue.Door, e, false);
                AudioRegistry.Clips(e.microphoneAudios, Cue.Broadcast);
                AudioRegistry.Clips(e.rareMicrophoneAudios, Cue.Broadcast);
                AudioRegistry.Clips(e.doorOpenSFX, Cue.Door);
                AudioRegistry.Clips(e.doorShutSFX, Cue.Door);
                AudioRegistry.Clips(e.rumbleSFX, Cue.GroundRumble);
                AudioRegistry.Clips(e.rewardGood, Cue.Creature);
                AudioRegistry.Clips(e.rewardBad, Cue.Creature);
                AudioRegistry.Source(e.rewardsMusic, Cue.TensionMusic, e, false);
                AudioRegistry.Source(e.speakerAudio, Cue.Broadcast, e, false);
                break;
            }
            case SnowmanSimpleAI e:
            {
                break;
            }
            case KiwiBabyItem e:
            {
                AudioRegistry.Source(e.eggAudio, Cue.BirdCall, e, false);
                AudioRegistry.Clips(e.peepAudio, Cue.EggCall);
                AudioRegistry.Clips(e.screamAudio, Cue.EggCry);
                AudioRegistry.Clips(e.breakEggSFX, Cue.EggBreak);
                AudioRegistry.Clips(e.scream3SFX, Cue.EggScream);
                break;
            }
            case HauntedMaskItem e:
            {
                AudioRegistry.Source(e.maskAudio, Cue.MaskLaugh, e, false);
                AudioRegistry.Clips(e.maskAttachAudio, Cue.MaskSound);
                AudioRegistry.Clips(e.maskAttachAudioLocal, Cue.MaskAttachLocal);
                break;
            }
            case SandSpiderWebTrap e:
            {
                AudioRegistry.Source(e.webAudio, Cue.Web, e, false);
                break;
            }
            case PlayerControllerB e:
            {
                AudioRegistry.RegisterFootsteps();
                AudioRegistry.Source(e.movementAudio, Cue.Creature, e, false);
                AudioRegistry.Source(e.slimeSlipAudio, Cue.Sliding, e, false);
                break;
            }
            case RoundManager e:
            {
                AudioRegistry.RegisterFootsteps();
                AudioRegistry.Clips(e.snowmanLaughSFX, Cue.Laughter);
                break;
            }
            case HighAndLowAltitudeAudio e:
            {
                AudioRegistry.Source(e.HighAudio, Cue.Environment, e, false);
                AudioRegistry.Source(e.LowAudio, Cue.Environment, e, false);
                AudioRegistry.Source(e.stopAudioAtTime, Cue.Environment, e, false);
                AudioRegistry.Source(e.NightAudio, Cue.Environment, e, false);
                break;
            }
            case PhysicsKnockbackOnHit e:
            {
                AudioRegistry.Clips(e.playSFX, Cue.Impact);
                break;
            }
            case TimeOfDay e:
            {
                AudioRegistry.Clips(e.timeOfDayCues, Cue.BackgroundMusic);
                AudioRegistry.Source(e.TimeOfDayMusic, Cue.BackgroundMusic, e, false);
                break;
            }
            case IngamePlayerSettings e:
            {
                AudioRegistry.Source(e.SettingsAudio, Cue.UiFeedback, e, false);
                break;
            }
            case ShipTeleporter e:
            {
                AudioRegistry.Source(e.buttonAudio, Cue.Teleport, e, false);
                AudioRegistry.Source(e.shipTeleporterAudio, Cue.Teleport, e, false);
                AudioRegistry.Clips(e.buttonPressSFX, Cue.Teleport);
                AudioRegistry.Clips(e.teleporterSpinSFX, Cue.Teleport);
                AudioRegistry.Clips(e.teleporterBeamUpSFX, Cue.Teleport);
                AudioRegistry.Clips(e.beamUpPlayerBodySFX, Cue.Teleport);
                break;
            }
            case AnimatedObjectFloatSetter e:
            {
                AudioRegistry.Source(e.thisAudio, Cue.Door, e, false);
                AudioRegistry.Clips(e.trueAudio, Cue.DoorOpen);
                AudioRegistry.Clips(e.falseAudio, Cue.DoorClose);
                AudioRegistry.Clips(e.completionTrueAudio, Cue.DoorOpen);
                AudioRegistry.Clips(e.completionFalseAudio, Cue.DoorClose);
                break;
            }
            case RadarBoosterItem e:
            {
                AudioRegistry.Source(e.pingAudio, Cue.RadarPing, e, false);
                AudioRegistry.Clips(e.pingSFX, Cue.RadarPing);
                AudioRegistry.Source(e.radarBoosterAudio, Cue.RadarSwitch, e, false);
                AudioRegistry.Clips(e.turnOnSFX, Cue.RadarSwitch);
                AudioRegistry.Clips(e.turnOffSFX, Cue.RadarSwitch);
                AudioRegistry.Clips(e.flashSFX, Cue.Electric);
                break;
            }
            case TVScript e:
            {
                AudioRegistry.Clips(e.tvAudioClips, Cue.Television);
                AudioRegistry.Clips(e.switchTVOn, Cue.Television);
                AudioRegistry.Clips(e.switchTVOff, Cue.Television);
                AudioRegistry.Source(e.tvSFX, Cue.Television, e, false);
                break;
            }
            case MicrowaveItem e:
            {
                AudioRegistry.Source(e.whirringAudio, Cue.Microwave, e, false);
                AudioRegistry.Clips(e.microwaveOpen, Cue.MicrowaveDoor);
                AudioRegistry.Clips(e.microwaveClose, Cue.MicrowaveDoor);
                break;
            }
            case CozyLights e:
            {
                AudioRegistry.Source(e.turnOnAudio, Cue.LightSwitch, e, false);
                break;
            }
            case GiftBoxItem e:
            {
                AudioRegistry.Source(e.presentAudio, Cue.GiftOpen, e, false);
                AudioRegistry.Clips(e.openGiftAudio, Cue.GiftOpen);
                break;
            }
            case BeltBagItem e:
            {
                AudioRegistry.Source(e.bagAudio, Cue.ItemNoise, e, false);
                AudioRegistry.Clips(e.zipUpBagSFX, Cue.BagZip);
                AudioRegistry.Clips(e.unzipBagSFX, Cue.BagZip);
                AudioRegistry.Clips(e.grabItemInBagSFX, Cue.ItemPickup);
                AudioRegistry.Clips(e.beltBagUnclipSFX, Cue.ItemNoise);
                break;
            }
            case EventWhenDroppedItem e:
            {
                AudioRegistry.Source(e.itemAudio, Cue.ItemDrop, e, false);
                break;
            }
            case DeadBodyInfo e:
            {
                AudioRegistry.Source(e.bodyAudio, Cue.BodyImpact, e, false);
                AudioRegistry.Source(e.playAudioOnDeath, Cue.BodyImpact, e, false);
                break;
            }
            case HUDManager e:
            {
                AudioRegistry.Clips(e.scanSFX, Cue.UiFeedback);
                AudioRegistry.Clips(e.addToScrapTotalSFX, Cue.UiFeedback);
                AudioRegistry.Clips(e.finishAddingToTotalSFX, Cue.UiFeedback);
                AudioRegistry.Source(e.UIAudio, Cue.UiFeedback, e, false);
                AudioRegistry.Clips(e.criticalInjury, Cue.Injury);
                AudioRegistry.Source(e.CriticalInjuryAudioSustain, Cue.Injury, e, false);
                AudioRegistry.Clips(e.criticalInjurySustain, Cue.Injury);
                AudioRegistry.Clips(e.globalNotificationSFX, Cue.UiFeedback);
                AudioRegistry.Clips(e.endStatsMusic, Cue.TensionMusic);
                AudioRegistry.Clips(e.shipAlarmHornSFX, Cue.UiWarning);
                AudioRegistry.Clips(e.radiationWarningAudio, Cue.UiWarning);
                AudioRegistry.Clips(e.meteorShowerWarningAudio, Cue.UiWarning);
                AudioRegistry.Clips(e.tipsSFX, Cue.UiFeedback);
                AudioRegistry.Clips(e.warningSFX, Cue.UiWarning);
                AudioRegistry.Source(e.dialogueBoxSFX, Cue.UiFeedback, e, false);
                AudioRegistry.Clips(e.dialogueBleeps, Cue.UiFeedback);
                AudioRegistry.Clips(e.advertMusic, Cue.UiFeedback);
                AudioRegistry.Clips(e.advertMusic2, Cue.UiFeedback);
                AudioRegistry.Source(e.breathingUnderwaterAudio, Cue.Underwater, e, false);
                AudioRegistry.Clips(e.levelIncreaseSFX, Cue.UiFeedback);
                AudioRegistry.Clips(e.levelDecreaseSFX, Cue.UiFeedback);
                AudioRegistry.Clips(e.decreaseXPSFX, Cue.UiFeedback);
                AudioRegistry.Clips(e.increaseXPSFX, Cue.UiFeedback);
                AudioRegistry.Source(e.LevellingAudio, Cue.UiFeedback, e, false);
                AudioRegistry.Clips(e.newProfitQuotaSFX, Cue.UiFeedback);
                AudioRegistry.Clips(e.reachedQuotaSFX, Cue.UiFeedback);
                AudioRegistry.Clips(e.OneDayToMeetQuotaSFX, Cue.UiWarning);
                AudioRegistry.Clips(e.profitQuotaDaysLeftCalmSFX, Cue.UiFeedback);
                AudioRegistry.Clips(e.displayCollectedScrapSFX, Cue.UiFeedback);
                AudioRegistry.Clips(e.displayCollectedScrapSFXSmall, Cue.UiFeedback);
                break;
            }
            case ShipBuildModeManager e:
            {
                AudioRegistry.Clips(e.beginPlacementSFX, Cue.UiFeedback);
                AudioRegistry.Clips(e.denyPlacementSFX, Cue.UiFeedback);
                AudioRegistry.Clips(e.cancelPlacementSFX, Cue.UiFeedback);
                AudioRegistry.Clips(e.storeItemSFX, Cue.UiFeedback);
                break;
            }
            case PlayAudioOnParticleDeath e:
            {
                AudioRegistry.Source(e.particleAudio, Cue.Impact, e, false);
                break;
            }
            case MoldSpreadManager e:
            {
                AudioRegistry.Source(e.destroyAudio, Cue.PlantClear, e, false);
                break;
            }
            case MoveToExitSpecialAnimation e:
            {
                AudioRegistry.Source(e.shockChairSound, Cue.Electric, e, false);
                break;
            }
            case RandomPeriodicAudioPlayer e:
            {
                AudioRegistry.Clips(e.randomClips, Cue.MaskSound);
                AudioRegistry.Source(e.thisAudio, Cue.MaskSound, e, false);
                break;
            }
            case BaboonHawkAudioEvents e:
            {
                AudioRegistry.Source(e.audioToPlay, Cue.Footsteps, e, false);
                AudioRegistry.Clips(e.randomClips, Cue.Footsteps);
                break;
            }
            case LoopShapeKey e:
            {
                AudioRegistry.Clips(e.audioOn, Cue.WorldHeartbeat);
                AudioRegistry.Clips(e.audioOff, Cue.WorldHeartbeat);
                AudioRegistry.Source(e.repeatingAudioSource, Cue.WorldHeartbeat, e, false);
                break;
            }
            case MeteorShowers e:
            {
                AudioRegistry.Clips(e.insideFactoryMeteorClip, Cue.MeteorImpact);
                break;
            }
            case ElevatorAnimationEvents e:
            {
                AudioRegistry.Source(e.audioToPlay, Cue.Elevator, e, false);
                AudioRegistry.Source(e.audioToPlay2, Cue.Elevator, e, false);
                break;
            }
            case DoorLock e:
            {
                AudioRegistry.Clips(e.pickingLockSFX, Cue.LockPicking);
                AudioRegistry.Clips(e.unlockSFX, Cue.Unlock);
                AudioRegistry.Source(e.doorLockSFX, Cue.LockPicking, e, false);
                break;
            }
            case LockPicker e:
            {
                AudioRegistry.Clips(e.placeLockPickerClips, Cue.LockPicking);
                AudioRegistry.Clips(e.finishPickingLockClips, Cue.Unlock);
                AudioRegistry.Source(e.lockPickerAudio, Cue.LockPicking, e, false);
                break;
            }
            case EnemyVent e:
            {
                AudioRegistry.Source(e.ventAudio, Cue.Vent, e, false);
                AudioRegistry.Clips(e.ventCrawlSFX, Cue.Vent);
                break;
            }
            case ItemCharger e:
            {
                AudioRegistry.Source(e.zapAudio, Cue.Charging, e, false);
                break;
            }
            case MineshaftElevatorController e:
            {
                AudioRegistry.Source(e.elevatorAudio, Cue.Elevator, e, false);
                AudioRegistry.Clips(e.elevatorStartUpSFX, Cue.Elevator);
                AudioRegistry.Clips(e.elevatorStartDownSFX, Cue.Elevator);
                AudioRegistry.Clips(e.elevatorTravelSFX, Cue.Elevator);
                AudioRegistry.Clips(e.elevatorFinishUpSFX, Cue.Elevator);
                AudioRegistry.Clips(e.elevatorFinishDownSFX, Cue.Elevator);
                AudioRegistry.Source(e.elevatorJingleMusic, Cue.ItemMusic, e, false);
                break;
            }
            case LungProp e:
            {
                AudioRegistry.Clips(e.connectSFX, Cue.Apparatus);
                AudioRegistry.Clips(e.disconnectSFX, Cue.Apparatus);
                AudioRegistry.Clips(e.removeFromMachineSFX, Cue.Apparatus);
                break;
            }
            case RemoteProp e:
            {
                AudioRegistry.Source(e.remoteAudio, Cue.Remote, e, false);
                break;
            }
            case ClockProp e:
            {
                AudioRegistry.Source(e.tickAudio, Cue.Clock, e, false);
                AudioRegistry.Clips(e.tickSFX, Cue.Clock);
                AudioRegistry.Clips(e.tockSFX, Cue.Clock);
                break;
            }
            case AnimatedItem e:
            {
                AudioRegistry.Source(e.itemAudio, Cue.ItemNoise, e, false);
                AudioRegistry.Clips(e.grabAudio, Cue.ItemNoise);
                AudioRegistry.Clips(e.dropAudio, Cue.ItemNoise);
                break;
            }
            case BreakerBox e:
            {
                AudioRegistry.Source(e.thisAudioSource, Cue.Breaker, e, false);
                AudioRegistry.Source(e.breakerBoxHum, Cue.PowerHum, e, false);
                AudioRegistry.Clips(e.switchPowerSFX, Cue.Breaker);
                break;
            }
            case Terminal e:
            {
                AudioRegistry.Source(e.terminalAudio, Cue.Terminal, e, false);
                AudioRegistry.Clips(e.keyboardClips, Cue.Terminal);
                AudioRegistry.Clips(e.syncedAudios, Cue.Terminal);
                AudioRegistry.Clips(e.codeBroadcastSFX, Cue.Terminal);
                AudioRegistry.Clips(e.enterTerminalSFX, Cue.Terminal);
                AudioRegistry.Clips(e.leaveTerminalSFX, Cue.Terminal);
                break;
            }
            case SpikeRoofTrap e:
            {
                AudioRegistry.Source(e.spikeTrapAudio, Cue.SpikeSlam, e, false);
                break;
            }
            case TetraChemicalItem e:
            {
                AudioRegistry.Source(e.localHelmetSFX, Cue.Inhaling, e, false);
                AudioRegistry.Source(e.thisAudioSource, Cue.Inhaling, e, false);
                AudioRegistry.Clips(e.twistCanSFX, Cue.Inhaling);
                AudioRegistry.Clips(e.releaseGasSFX, Cue.Inhaling);
                AudioRegistry.Clips(e.holdCanSFX, Cue.Inhaling);
                AudioRegistry.Clips(e.removeCanSFX, Cue.TzpRelease);
                AudioRegistry.Clips(e.outOfGasSFX, Cue.TzpEmpty);
                break;
            }
            case PatcherTool e:
            {
                AudioRegistry.Source(e.mainAudio, Cue.Zap, e, false);
                AudioRegistry.Source(e.shockAudio, Cue.Zap, e, false);
                AudioRegistry.Source(e.gunAudio, Cue.Zap, e, false);
                AudioRegistry.Clips(e.activateClips, Cue.Zap);
                AudioRegistry.Clips(e.beginShockClips, Cue.Zap);
                AudioRegistry.Clips(e.overheatClips, Cue.EquipmentWarning);
                AudioRegistry.Clips(e.finishShockClips, Cue.Zap);
                AudioRegistry.Clips(e.outOfBatteriesClip, Cue.BatteryWarning);
                AudioRegistry.Clips(e.detectAnomaly, Cue.Zap);
                AudioRegistry.Clips(e.scanAnomaly, Cue.Zap);
                break;
            }
            case StartOfRound e:
            {
                AudioRegistry.Clips(e.changeSuitSFX, Cue.SuitChange);
                AudioRegistry.Source(e.shipAmbianceAudio, Cue.ShipHum, e, false);
                AudioRegistry.Source(e.shipMotorAudio, Cue.ShipHum, e, false);
                AudioRegistry.Clips(e.shipDepartSFX, Cue.ShipTravel);
                AudioRegistry.Clips(e.shipArriveSFX, Cue.ShipArrival);
                AudioRegistry.Source(e.shipDoorAudioSource, Cue.ShipDoor, e, false);
                AudioRegistry.Source(e.speakerAudioSource, Cue.Broadcast, e, false);
                AudioRegistry.Clips(e.suckedIntoSpaceSFX, Cue.Underwater);
                AudioRegistry.Clips(e.shipCreakSFX, Cue.ShipMechanism);
                AudioRegistry.Clips(e.alarmSFX, Cue.Alarm);
                AudioRegistry.Clips(e.firedVoiceSFX, Cue.Broadcast);
                AudioRegistry.Clips(e.openingHangarDoorAudio, Cue.ShipDoor);
                AudioRegistry.Clips(e.shipIntroSpeechSFX, Cue.Broadcast);
                AudioRegistry.Clips(e.disableSpeakerSFX, Cue.Broadcast);
                AudioRegistry.Clips(e.zeroDaysLeftAlertSFX, Cue.Broadcast);
                AudioRegistry.Source(e.startGameWhir, Cue.ShipLanding, e, false);
                AudioRegistry.Source(e.shipLandingAudio, Cue.ShipLanding, e, false);
                AudioRegistry.Source(e.shipLandingScrapAudio, Cue.ItemDrop, e, false);
                AudioRegistry.Source(e.shipDoorsClosingJingle, Cue.ShipMechanism, e, false);
                AudioRegistry.Clips(e.HUDSystemAlertSFX, Cue.UiWarning);
                AudioRegistry.Clips(e.damageSFX, Cue.Injury);
                AudioRegistry.Clips(e.fallDamageSFX, Cue.Injury);
                AudioRegistry.Clips(e.bloodGoreSFX, Cue.BodyImpact);
                AudioRegistry.Clips(e.playerShoveSFX, Cue.BodyImpact);
                AudioRegistry.Clips(e.playerGrabSFX, Cue.ItemPickup);
                AudioRegistry.Clips(e.bodyCollisionSFX, Cue.BodyImpact);
                AudioRegistry.Clips(e.playerFallDeath, Cue.DeathSound);
                AudioRegistry.Clips(e.playerCrushDeath, Cue.BodyCrush);
                AudioRegistry.Clips(e.hitPlayerSFX, Cue.BodyImpact);
                break;
            }
            case StormyWeather e:
            {
                AudioRegistry.Clips(e.strikeSFX, Cue.Thunder);
                AudioRegistry.Clips(e.distantThunderSFX, Cue.Thunder);
                AudioRegistry.Source(e.randomStrikeAudio, Cue.Thunder, e, false);
                AudioRegistry.Source(e.randomStrikeAudioB, Cue.Thunder, e, false);
                AudioRegistry.Source(e.targetedStrikeAudio, Cue.Thunder, e, false);
                AudioRegistry.Clips(e.staticElectricityAudio, Cue.StaticWarning);
                break;
            }
            case BridgeTrigger e:
            {
                AudioRegistry.Source(e.bridgeAudioSource, Cue.BridgeCreak, e, false);
                AudioRegistry.Clips(e.bridgeCreakSFX, Cue.BridgeCreak);
                AudioRegistry.Clips(e.bridgeFallSFX, Cue.BridgeCollapse);
                break;
            }
            case ShipAlarmCord e:
            {
                AudioRegistry.Source(e.hornClose, Cue.Horn, e, true);
                AudioRegistry.Source(e.hornFar, Cue.Horn, e, true);
                AudioRegistry.Source(e.cordAudio, Cue.MechanicalTurn, e, false);
                AudioRegistry.Clips(e.cordPullSFX, Cue.MechanicalTurn);
                break;
            }
            case JetpackItem e:
            {
                AudioRegistry.Source(e.jetpackAudio, Cue.Jetpack, e, false);
                AudioRegistry.Source(e.jetpackBeepsAudio, Cue.EquipmentWarning, e, false);
                AudioRegistry.Clips(e.startJetpackSFX, Cue.Jetpack);
                AudioRegistry.Clips(e.jetpackSustainSFX, Cue.Jetpack);
                AudioRegistry.Clips(e.jetpackBrokenSFX, Cue.EquipmentWarning);
                AudioRegistry.Clips(e.jetpackWarningBeepSFX, Cue.EquipmentWarning);
                AudioRegistry.Clips(e.jetpackLowBatteriesSFX, Cue.BatteryWarning);
                break;
            }
            case StunGrenadeItem e:
            {
                AudioRegistry.Source(e.itemAudio, Cue.Explosion, e, false);
                AudioRegistry.Clips(e.pullPinSFX, Cue.PinPull);
                AudioRegistry.Clips(e.explodeSFX, Cue.Explosion);
                break;
            }
            case ExtensionLadderItem e:
            {
                AudioRegistry.Clips(e.hitRoof, Cue.Impact);
                AudioRegistry.Clips(e.fullExtend, Cue.Ladder);
                AudioRegistry.Clips(e.hitWall, Cue.Impact);
                AudioRegistry.Clips(e.ladderExtendSFX, Cue.Ladder);
                AudioRegistry.Clips(e.ladderFallSFX, Cue.Ladder);
                AudioRegistry.Clips(e.ladderShrinkSFX, Cue.Ladder);
                AudioRegistry.Clips(e.blinkWarningSFX, Cue.EquipmentWarning);
                AudioRegistry.Clips(e.lidOpenSFX, Cue.Ladder);
                AudioRegistry.Source(e.ladderAudio, Cue.Ladder, e, false);
                break;
            }
            case Shovel e:
            {
                AudioRegistry.Clips(e.reelUp, Cue.ToolSwing);
                AudioRegistry.Clips(e.swing, Cue.ToolSwing);
                AudioRegistry.Clips(e.hitSFX, Cue.Impact);
                AudioRegistry.Source(e.shovelAudio, Cue.ToolSwing, e, false);
                break;
            }
            case KnifeItem e:
            {
                AudioRegistry.Source(e.knifeAudio, Cue.ToolSwing, e, false);
                AudioRegistry.Clips(e.hitSFX, Cue.Impact);
                AudioRegistry.Clips(e.swingSFX, Cue.ToolSwing);
                break;
            }
            case SprayPaintItem e:
            {
                AudioRegistry.Source(e.sprayAudio, Cue.SprayPaint, e, false);
                AudioRegistry.Clips(e.spraySFX, Cue.SprayPaint);
                AudioRegistry.Clips(e.sprayNeedsShakingSFX, Cue.CanShake);
                AudioRegistry.Clips(e.sprayStart, Cue.SprayPaint);
                AudioRegistry.Clips(e.sprayStop, Cue.SprayPaint);
                AudioRegistry.Clips(e.sprayCanEmptySFX, Cue.CanShake);
                AudioRegistry.Clips(e.sprayCanNeedsShakingSFX, Cue.CanShake);
                AudioRegistry.Clips(e.sprayCanShakeEmptySFX, Cue.CanShake);
                AudioRegistry.Clips(e.sprayCanShakeSFX, Cue.CanShake);
                break;
            }
            case FlashlightItem e:
            {
                AudioRegistry.Source(e.flashlightAudio, Cue.FlashlightSwitch, e, false);
                AudioRegistry.Clips(e.flashlightClips, Cue.FlashlightSwitch);
                AudioRegistry.Clips(e.outOfBatteriesClip, Cue.BatteryWarning);
                break;
            }
            case Turret e:
            {
                AudioRegistry.Source(e.mainAudio, Cue.MechanicalAlert, e, false);
                AudioRegistry.Source(e.bulletCollisionAudio, Cue.Ricochet, e, false);
                AudioRegistry.Source(e.farAudio, Cue.Gunshot, e, true);
                AudioRegistry.Clips(e.firingSFX, Cue.Gunshot);
                AudioRegistry.Clips(e.chargingSFX, Cue.Alarm);
                AudioRegistry.Clips(e.detectPlayerSFX, Cue.Alarm);
                AudioRegistry.Clips(e.firingFarSFX, Cue.Gunshot);
                AudioRegistry.Clips(e.bulletsHitWallSFX, Cue.Ricochet);
                AudioRegistry.Clips(e.turretActivate, Cue.MechanicalAlert);
                AudioRegistry.Clips(e.turretDeactivate, Cue.MechanicalAlert);
                AudioRegistry.Source(e.berserkAudio, Cue.Alarm, e, false);
                break;
            }
            case Landmine e:
            {
                AudioRegistry.Source(e.mineAudio, Cue.MineBeep, e, false);
                AudioRegistry.Source(e.mineFarAudio, Cue.Explosion, e, false);
                AudioRegistry.Clips(e.mineDetonate, Cue.Explosion);
                AudioRegistry.Clips(e.mineTrigger, Cue.MinePress);
                AudioRegistry.Clips(e.mineDetonateFar, Cue.Explosion);
                AudioRegistry.Clips(e.mineDeactivate, Cue.MineBeep);
                AudioRegistry.Clips(e.minePress, Cue.MinePress);
                break;
            }
            case SteamValveHazard e:
            {
                AudioRegistry.Clips(e.pipeFlowingSFX, Cue.PipeFlow);
                AudioRegistry.Clips(e.valveTwistSFX, Cue.MechanicalTurn);
                AudioRegistry.Clips(e.valveBurstSFX, Cue.PipeBurst);
                AudioRegistry.Clips(e.valveCrackSFX, Cue.Crack);
                AudioRegistry.Clips(e.steamBlowSFX, Cue.Steam);
                AudioRegistry.Source(e.valveAudio, Cue.PipeFlow, e, false);
                break;
            }
            case SoundManager e:
            {
                AudioRegistry.Source(e.ambienceAudio, Cue.Environment, e, false);
                AudioRegistry.Source(e.ambienceAudioNonDiagetic, Cue.Environment, e, false);
                AudioRegistry.Source(e.musicSource, Cue.BackgroundMusic, e, false);
                AudioRegistry.Clips(e.DaytimeMusic, Cue.BackgroundMusic);
                AudioRegistry.Clips(e.EveningMusic, Cue.BackgroundMusic);
                AudioRegistry.Source(e.highAction1, Cue.TensionMusic, e, false);
                AudioRegistry.Source(e.highAction2, Cue.TensionMusic, e, false);
                AudioRegistry.Source(e.lowAction, Cue.TensionMusic, e, false);
                AudioRegistry.Source(e.heartbeatSFX, Cue.Heartbeat, e, false);
                AudioRegistry.Clips(e.heartbeatClips, Cue.Heartbeat);
                AudioRegistry.Source(e.poisonAudio, Cue.PoisonFeedback, e, false);
                AudioRegistry.Source(e.ringingEarsAudio, Cue.EarRinging, e, false);
                AudioRegistry.Source(e.ringingEarsAudio2, Cue.EarRinging, e, false);
                AudioRegistry.Clips(e.waterSplashSFX, Cue.Liquid);
                AudioRegistry.Clips(e.waterSplashSFXSmall, Cue.Liquid);
                AudioRegistry.Clips(e.steelDoorOpenSFX, Cue.DoorOpen);
                AudioRegistry.Clips(e.steelDoorCloseSFX, Cue.DoorClose);
                AudioRegistry.Clips(e.woodDoorOpenSFX, Cue.DoorOpen);
                AudioRegistry.Clips(e.woodDoorCloseSFX, Cue.DoorClose);
                break;
            }
            case EntranceTeleport e:
            {
                AudioRegistry.Source(e.entrancePointAudio, Cue.Door, e, false);
                AudioRegistry.Clips(e.doorAudios, Cue.Door);
                break;
            }
            case VehicleController e:
            {
                AudioRegistry.Source(e.engineAudio1, Cue.VehicleEngine, e, true);
                AudioRegistry.Source(e.engineAudio2, Cue.VehicleEngine, e, true);
                AudioRegistry.Source(e.rollingAudio, Cue.VehicleEngine, e, true);
                AudioRegistry.Source(e.turbulenceAudio, Cue.VehicleImpact, e, true);
                AudioRegistry.Clips(e.revEngineStart, Cue.CruiserIgnition);
                AudioRegistry.Clips(e.engineStartSuccessful, Cue.CruiserStarted);
                AudioRegistry.Clips(e.engineRun, Cue.VehicleEngine);
                AudioRegistry.Clips(e.engineRev, Cue.CruiserIgnition);
                AudioRegistry.Clips(e.engineRun2, Cue.VehicleEngine);
                AudioRegistry.Clips(e.insertKey, Cue.CruiserKey);
                AudioRegistry.Clips(e.twistKey, Cue.CruiserKey);
                AudioRegistry.Clips(e.removeKey, Cue.CruiserKey);
                AudioRegistry.Clips(e.sitDown, Cue.VehicleInteraction);
                AudioRegistry.Source(e.tireAudio, Cue.Skidding, e, false);
                AudioRegistry.Source(e.vehicleEngineAudio, Cue.VehicleEngine, e, true);
                AudioRegistry.Source(e.steeringWheelAudio, Cue.VehicleInteraction, e, false);
                AudioRegistry.Source(e.skiddingAudio, Cue.Skidding, e, false);
                AudioRegistry.Source(e.gearStickAudio, Cue.VehicleInteraction, e, false);
                AudioRegistry.Clips(e.gearStickAudios, Cue.VehicleInteraction);
                AudioRegistry.Source(e.hoodAudio, Cue.VehicleInteraction, e, false);
                AudioRegistry.Source(e.pushAudio, Cue.VehicleInteraction, e, false);
                AudioRegistry.Source(e.collisionAudio1, Cue.VehicleImpact, e, true);
                AudioRegistry.Source(e.collisionAudio2, Cue.VehicleImpact, e, true);
                AudioRegistry.Clips(e.maxCollisions, Cue.VehicleImpact);
                AudioRegistry.Clips(e.medCollisions, Cue.VehicleImpact);
                AudioRegistry.Clips(e.minCollisions, Cue.VehicleImpact);
                AudioRegistry.Clips(e.obstacleCollisions, Cue.VehicleImpact);
                AudioRegistry.Clips(e.windshieldBreak, Cue.VehicleImpact);
                AudioRegistry.Source(e.miscAudio, Cue.VehicleInteraction, e, false);
                AudioRegistry.Source(e.radioAudio, Cue.RadioMusic, e, false);
                AudioRegistry.Source(e.hoodFireAudio, Cue.VehicleFire, e, false);
                AudioRegistry.Clips(e.carHoodOpenSFX, Cue.CruiserHood);
                AudioRegistry.Clips(e.carHoodCloseSFX, Cue.CruiserHood);
                AudioRegistry.Clips(e.headlightsToggleSFX, Cue.VehicleInteraction);
                AudioRegistry.Source(e.springAudio, Cue.SeatEject, e, false);
                AudioRegistry.Source(e.hornAudio, Cue.Horn, e, false);
                AudioRegistry.Source(e.extremeStressAudio, Cue.EquipmentWarning, e, false);
                AudioRegistry.Source(e.turboBoostAudio, Cue.VehicleBoost, e, true);
                AudioRegistry.Clips(e.turboBoostSFX, Cue.VehicleBoost);
                AudioRegistry.Clips(e.turboBoostSFX2, Cue.VehicleBoost);
                AudioRegistry.Clips(e.jumpInCarSFX, Cue.VehicleJump);
                AudioRegistry.Clips(e.pourTurbo, Cue.VehicleRefuel);
                break;
            }
            case NoisemakerProp e:
            {
                AudioRegistry.Source(e.noiseAudio, Cue.ItemNoise, e, true);
                AudioRegistry.Source(e.noiseAudioFar, Cue.ItemNoise, e, true);
                AudioRegistry.Clips(e.noiseSFX, Cue.ItemNoise);
                AudioRegistry.Clips(e.noiseSFXFar, Cue.ItemNoise);
                break;
            }
            case BoomboxItem e:
            {
                AudioRegistry.Source(e.boomboxAudio, Cue.ItemMusic, e, false);
                AudioRegistry.Clips(e.musicAudios, Cue.ItemMusic);
                AudioRegistry.Clips(e.stopAudios, Cue.ItemNoise);
                break;
            }
            case WhoopieCushionItem e:
            {
                AudioRegistry.Source(e.whoopieCushionAudio, Cue.Cushion, e, false);
                AudioRegistry.Clips(e.fartAudios, Cue.Cushion);
                break;
            }
            case WalkieTalkie e:
            {
                AudioRegistry.Clips(e.stopTransmissionSFX, Cue.RadioSignal);
                AudioRegistry.Clips(e.startTransmissionSFX, Cue.RadioSignal);
                AudioRegistry.Clips(e.switchWalkieTalkiePowerOff, Cue.RadioSignal);
                AudioRegistry.Clips(e.switchWalkieTalkiePowerOn, Cue.RadioSignal);
                AudioRegistry.Clips(e.talkingOnWalkieTalkieNotHeldSFX, Cue.RadioSignal);
                AudioRegistry.Clips(e.playerDieOnWalkieTalkieSFX, Cue.RadioSignal);
                AudioRegistry.Source(e.wallAudio, Cue.RadioMusic, e, false);
                AudioRegistry.Clips(e.wallAudios, Cue.RadioMusic);
                break;
            }
        }
    }
}
